- name: Enable br_netfilter
  become: true
  community.general.modprobe:
    name: br_netfilter
    state: present
    persistent: present
- name: Enable sysctl functions for kubernetes
  become: true
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    sysctl_set: true
    state: present
    reload: true
  loop:
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-arptables
    - net.bridge.bridge-nf-call-ip6tables
