# на мастере
# kubeadm token create --print-join-command
#
- name: Copy join command to worker nodes.
  ansible.builtin.copy:
    src: /tmp/kubernetes_join_command
    dest: /tmp/kubernetes_join_command
    mode: "0777"

- name: RUN JOIN to CLUSTER if file is present
  ansible.builtin.stat:
    path: /etc/kubernetes/pki/ca.crt
  register: join_status

- name: Join to cluster
  become: true
  become_user: root
  when: not join_status.stat.exists
  block:
    - name: Join the Worker nodes with the master.
      ansible.builtin.command: sh /tmp/kubernetes_join_command
      register: joined_or_not
      changed_when:
        - "'This node has joined the cluster' in joined_or_not.stdout"
      failed_when:
        - joined_or_not.rc != 0
    - name: Get info about joined nodes
      ansible.builtin.debug:
        msg: "{{ ansible_hostname }} - This node has joined the cluster"
      when:
        - joined_or_not.rc == 0
      changed_when:
        - "'This node has joined the cluster' in joined_or_not.stdout"
