---
- name: Get public IP
  community.general.ipify_facts:
  timeout: 20

- debug:
    msg: "{{ hostvars.master1.ipify_public_ip }}"

- name: Store file for ./kube/config to localhost
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: "{{ kubeadm_local.config_path | default('~/.kube/config') }}"
    flat: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  become: true
  become_user: root

- name: Change file ownership, group and permissions to ~/.kube/config
  ansible.builtin.file:
    path: "{{ kubeadm_local.config_path | default('~/.kube/config') }}"
    owner: "{{ kubeadm_local.user | default(lookup('env', 'USER')) }}"
    group: "{{ kubeadm_local.user | default(lookup('env', 'USER')) }}"
    mode: '0600'
  delegate_to: localhost

- name: Change endpoint server to FQDN
  ansible.builtin.lineinfile:
    path: "{{ kubeadm_local.config_path | default('~/.kube/config') }}"
    search_string: "    server: https:"
    line: "    server: https://{{ kubeadm_kube_settings.fqdn }}:6443"
  delegate_to: localhost
  when: "kubeadm_kube_settings.fqdn is defined and kubeadm_kube_settings.fqdn|length>0"

- name: Change endpoint server to external IP
  ansible.builtin.lineinfile:
    path: "{{ kubeadm_local.config_path | default('~/.kube/config') }}"
    search_string: "    server: https:"
    line: "    server: https://{{ hostvars.master1.ipify_public_ip }}:6443"
  delegate_to: localhost
  when: "kubeadm_kube_settings.fqdn is undefined or kubeadm_kube_settings.fqdn| length<2 "
