- name: CNI | Check FLANNEL
  become: true
  ansible.builtin.stat:
    path: /var/kuber_cni_flannel_inited.txt
  register: stat_flannel

- name: Create Pod Network Flannel.
  ansible.builtin.include_tasks: 11_cni-flannel.yml
  when:
    - kubeadm_cni.flannel | default(false)
    - not stat_flannel.stat.exists

- name: CNI | Check CALICO
  become: true
  ansible.builtin.stat:
    path: /var/kuber_cni_calico_inited.txt
  register: stat_calico

- name: Create Pod Network Calico.
  ansible.builtin.include_tasks: 12_cni-calico.yml
  when:
    - ( kubeadm_cni.calico | default(false) ) or ( kubeadm_cni.canal_calico | default(false) )
    - not stat_calico.stat.exists
