# https://github.com/flannel-io/flannel

- name: FLUNNEL | Install Flunnel
  block:
    - name: FLUNNEL | Generate Flunnel custom resource
      become: true
      ansible.builtin.template:
        src: flunnel_resources.j2
        dest: /opt/flunnel_resources.yaml
        mode: "0644"
    - name: FLUNNEL | Install Flunnel by creating the necessary custom resource
      ansible.builtin.command: "{{ item }}"
      with_items:
        - kubectl apply -f /opt/flunnel_resources.yaml
      register: cni_flunnel_complete
      changed_when: cni_flunnel_complete.rc == 0
