# https://github.com/flannel-io/flannel

- name: FLUNNEL | Install Flunnel
  block:
    - name: FLUNNEL | Generate Flunnel custom resource
      become: true
      ansible.builtin.template:
        src: flunnel_resources.j2
        dest: /opt/flunnel_resources.yaml
        mode: "0644"
    - name: FLUNNEL | Install Flunnel by creating the necessary custom resource
      ansible.builtin.command: "{{ item }}"
      with_items:
        - kubectl apply -f /opt/flunnel_resources.yaml
      register: cni_flunnel_complete
      changed_when: cni_flunnel_complete.rc == 0
    - name: Make file that task already completed
      ansible.builtin.file:
        path: /var/kuber_cni_flunnel_inited.txt
        state: touch
        owner: root
        group: root
        mode: '0644'
      become: true
