# https://docs.tigera.io/calico/latest/getting-started/kubernetes/quickstart

- name: CALICO | Install the Tigera Calico operator and custom resource definitions.
  ansible.builtin.command: "{{ item }}"
  with_items:
    - kubectl create -f {{ kubeadm_cni_conf.calico.url_dist_tigra }}
  register: cni_calico_tigera_complete
  changed_when: cni_calico_tigera_complete.rc == 0

- name: CALICO | Install Calico
  block:
    - name: CALICO | Generate Calico custom resource
      become: true
      ansible.builtin.template:
        src: calico_resources.j2
        dest: /opt/calico_resources.yaml
        mode: "0644"
    - name: CALICO | Install Calico by creating the necessary custom resource
      ansible.builtin.command: "{{ item }}"
      with_items:
        - kubectl create -f /opt/calico_resources.yaml
      register: cni_calico_complete
      changed_when: cni_calico_complete.rc == 0
