---
- name: SYSTEM | Prepare OS
  ansible.builtin.include_tasks: 01_prepare.yml
  when: (ansible_hostname in groups['kube_node']) or
        (ansible_hostname in groups['kube_control_plane'])
  tags: prepare

- name: SYSTEM | Install Kubeadm tools
  ansible.builtin.include_tasks: 02_install.yml
  when: (ansible_hostname in groups['kube_node']) or
        (ansible_hostname in groups['kube_control_plane'])
  tags: install

# - name: KUBERNETES | Enable HA for cluster
#   ansible.builtin.include_tasks: 08_ha-baremetal.yml
#   when:
#     - ansible_hostname in groups['kube_control_plane']
#   tags: ha_enable

- name: SYSTEM | Hosts configured
  ansible.builtin.include_tasks: 03_host-config.yml
  when: (ansible_hostname in groups['kube_node']) or
        (ansible_hostname in groups['kube_control_plane'])
  tags: confirure

- name: KUBERNETES | Init cluster Kubernetes
  ansible.builtin.include_tasks: 04_init.yml
  when: ansible_hostname in groups['kube_control_plane'][0]
  tags: initka

- name: KUBERNETES | Get config file
  ansible.builtin.include_tasks: 06_get-config.yml
  when:
    - ansible_hostname in groups['kube_control_plane'][0]
    - kubeadm_local.make_config | default(false)
  tags: get_config

- name: KUBERNETES | Join masters nodes to cluster
  ansible.builtin.include_tasks: 07_join-mastes.yml
  when:
    - ansible_hostname in groups['kube_control_plane']
  tags: joinka_masters

- name: KUBERNETES | Install Network plugins
  ansible.builtin.include_tasks: 10_cni.yml
  when: ansible_hostname in groups['kube_control_plane'][0]
  tags: cni_install

- name: KUBERNETES | Join worker nodes to cluster
  ansible.builtin.include_tasks: 05_join.yml
  when:
    - ansible_hostname in groups['kube_node']
  tags: joinka

- name: KUBERNETES | Install Ingress-nginx controller
  ansible.builtin.include_tasks: 21_ingress_nginx.yml
  when: ansible_hostname in groups['kube_control_plane'][0]
  tags: ingress_install

- name: KUBERNETES | Install Argo CD
  ansible.builtin.include_tasks: 31_argocd.yml
  when: ansible_hostname in groups['kube_control_plane'][0]
  tags: argocd_install

- name: KUBERNETES | Argo CD create root application
  ansible.builtin.include_tasks: 32_argocd_root-app.yml
  when:
    - kubeadm_argocd_root.enable
    - ansible_hostname in groups['kube_control_plane'][0]
  tags: argocd_root
