---
# handlers file for ansible-kubeadm
- name: Restart service containerd
  become: true
  ansible.builtin.service:
    state: restarted
    name: containerd

- name: Restart service haproxy
  become: true
  ansible.builtin.service:
    state: restarted
    enabled: true
    name: haproxy
